; Custom php.ini for local built-in server
; Enable essential MySQL extensions
extension_dir = "C:\\php\\ext"
extension = pdo_mysql
enable_dl = Off
extension = mysqli

; Common settings
date.timezone = Asia/Seoul
mbstring.language = Korean
mbstring.func_overload = 0
expose_php = Off

; Error reporting (dev)
display_errors = On
log_errors = On
error_reporting = E_ALL